### ISSUE TITLE
Vital Signs not supported for DIAGNOSE

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#32]
I could not even save a case which included this category.
you can open the case: 
A case of Chronic Renal Failure

try to add a new finding.
1. choose "Vital signs" category
2. select Hypertension (high / low)

see that now you can not diagnose or even save the case

**Comment by alex8080** [comment]
The "Hypertension (high/low)" is a "VITAL SIGN". According to the code any "VITAL SIGN" should have a "procedure" associated. Is it a correct assumption? "Hypertension" does not have procedure associated and as a result the "Finding" line never complete. 
If not having all the information is valid I will fix the code. 
Otherwise, I could probably filter out such features from the feature selection list.

@kahunmedicaltal your thoughts?

**Comment by kahunmedicaltal** [comment]
checking

**Comment by kahunmedicaltal** [comment]
Alex, you are right. As the system is built now, each VITAL SIGN should have a procedure attached 
 to it. Right solution would be to attach a procedure to vital signs.

**Comment by alex8080** [comment]
Hi Tal,

Do you recall the reason you commented out the check that a vital sign has a procedure associated to enable feature save button? https://github.com/kahunmedical/kne.fe/blob/master/src/components/featureEdit/featureForm.tsx#L199

**Comment by kahunmedicaltal** [comment]
Good question

(1) The concept is that each feature (of the hasProcedure() types) must
have a procedure(s) attached to it and
(2) each time the feature is selected (as either the "then" part of a rule
or in the cases page) a procedure out of the feature's list has to be
attached to it.

At some point of time (due to michal's request)  we have eased this
restriction and enabled attaching, in (2), any procedure thus listing
procedure list next to the feature became optional (and thus the commented
code)

We are still not 100% sure about the right approach here. However, the
current approach is to force a feature having procedures and in the cases
page select a procedure out of it's list.

**Comment by eitan-ron** [comment]
Even after i added  the BLOOD PRESSURE PANEL, the problem persists

**Comment by kahunmedicaltal** [comment]
@eitan-ron - 
you should first :
1. go to the "features" menu 
2. select "HTN - Hypertension"
3. Select possible procedures to detect Hypertension (if non, exists, you would need to define one under the "procedures" menu
4. Go back to the cases page and select the relevant procedure along with "HTN - Hypertension"

BTW - there are no rules currently attached to "HTN - Hypertension" (http://ec2-18-217-18-129.us-east-2.compute.amazonaws.com/#/w-kahun/feature/FE.d7c2d221-1096-4cd9-a5c4-f6aa2a586cf2) so adding it to the case is meaningless.

**Comment by kahunmedicaltal** [comment]
Eitan - still relevant? if not, lets close
