### ISSUE TITLE
in Diagnose - showing same test multiple times

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#37]
To reconstruct:
Select A case of BACTERIAL PERITONITIS.   Diagnose.
You'll see that some tests are repeated, e.g. the one below :

IMAGING, Ileitis (disorder)Add to Case | 0.1629 | 2006.0000 | 0.0001
IMAGING, Ileitis (disorder)Add to Case | 0.1629 | 367.0000 | 0.0004
IMAGING, Ileitis (disorder)Add to Case | 0.1629 | 440.0000 | 0.0004

**Comment by kahunmedicaltal** [comment]
@alex8080 - as far as I could understand this is a single feature with 3 different procedures

The feature is : 
FE.edf00549-fd4a-44b2-94c5-d8690069681a

And the procedures are:
 PR.505a3289-2c35-44f1-a477-7728fb91aec4
 PR.7ae9ff6e-b568-4e35-9980-585adff5616e
 PR.a8935a0a-c1c7-4760-87a3-f0d0a6fbeae0

However, for some reason, once you select "Add to Case" Kahun always adds it with the 1st procedure instead of the relevant one. Could you please look into this?
