### ISSUE TITLE
SOLVER: grouping of findings inconsistency

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#390]
Cannot figure out why 'Digestive system finding' as a group is not working in SOME of the diseases. 
Example: In Systemic sclerosis - works the same as other groups
Example: in Celiac disease - in the symptoms section, the GI symptoms are not grouped into this group.
This is the group in question : http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/featureEdit/FE.035cffd4-04ce-4ca4-ab81-28837ad40ce9

Please help !!

**Comment by shaharov** [comment]
We have that _Celiac_ isa _Digestive system finding_. We had a rule of thumb to remove all ISAs findings from the disease view because  P(F|D)=100% so we found these findings as not interesting.  (Probably they should appear in different section)

However, I made so change, so features with _groupBy:true_  are now back to disease view (https://github.com/kahunmedical/kne.graphql/commit/8fce66a949d4567f4af569cdc10634576ebd1c91), so you should see  _Digestive system finding_ in Celiac disease view.

**Comment by MichalKahun** [comment]
The finding is now viewed in the correct tab, thanks.
