### ISSUE TITLE
Better show of etilogy rules 

### ISSUE THREAD

**Issue by kahunmedicaltal** [kahunmedical/kne#417]
Stop reversing rules using bayes - 

In case the path we have is from D to F show P(F|D)
In case the path we have is from F to D show lift as P(D|F)/P(D)

**Comment by shaharov** [comment]
If we have paths from D to F then we set `ClinicalReasoningFinding.basedOnFindingGivenDisease` to be `true`, otherwise it is `false`.

The field `ClinicalReasoningFinding.lift` is equal to `P(F|D)/P(F)` if the above boolean is true,  or , `P(D|F)/P(D)`, otherwise

So, to be more concrete, in case the path we have is from D to F (the above boolean is `true`) the UI should show  `ClinicalReasoningFinding.findingGivenDisease = P(F|D)` 
In case the path we have is from F to D (the above boolean is `false`) the UI should show `ClinicalReasoningFinding.lift=P(D|F)/P(D)`.
